### ISSUE TITLE
unable to use _.toInteger() in n_ repl - how can I force lodash major version 4?

### ISSUE THREAD

**Issue by paul42** [borisdiakur/n_#22]
Hey @borisdiakur love your library, but I think I'm doing something wrong, I can't get _.toInteger() to work, I get an error - when I install globally I think it's still doing lodash major v 3?

```
paul42$ npm install -g n_
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
/Users/paul42/.nvm/versions/node/v8.7.0/bin/n_3 -> /Users/paul42/.nvm/versions/node/v8.7.0/lib/node_modules/n_/bin/n_3
/Users/paul42/.nvm/versions/node/v8.7.0/bin/n_ -> /Users/paul42/.nvm/versions/node/v8.7.0/lib/node_modules/n_/bin/n_

> n_@1.4.5 postinstall /Users/paul42/.nvm/versions/node/v8.7.0/lib/node_modules/n_
> npm pack lodash@^3 && targz extract lodash-3.*.tgz extraneous/lodash3

lodash-3.10.1.tgz
+ n_@1.4.5
added 26 packages in 3.564s
paul42:crm-api-rva paul42$ n_4
-bash: n_4: command not found
paul42:crm-api-rva paul42$ n_3
n_ > _.toInteger('4')
TypeError: _.toInteger is not a function
    at repl:1:3
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at REPLServer.defaultEval (repl.js:241:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at Array.onLine (repl.js:440:10)
    at REPLServer.<anonymous> (/Users/paul42/.nvm/versions/node/v8.7.0/lib/node_modules/n_/lib/n_.js:75:12)
    at REPLServer.wrapper (/Users/paul42/.nvm/versions/node/v8.7.0/lib/node_modules/n_/extraneous/lodash3/package/index.js:3592:19)
    at emitOne (events.js:115:13)
    at REPLServer.emit (events.js:210:7)
n_ > 
```

let me know if there is a certain area I can look at to submit a pull request. thanks for the awesome library!

**Comment by borisdiakur** [comment]
Hi Paul. There is currently no `n_4` command. Not until lodash v5 is out. The `n_3` command starts the REPL with lodash v3 included, which doesn’t have the `toInteger` method. Have you tried using the command `n_` (need to ask because I do not see it above)?

Here is my output:

```
$ npm i -g n_
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
/usr/local/bin/n_ -> /usr/local/lib/node_modules/n_/bin/n_
/usr/local/bin/n_3 -> /usr/local/lib/node_modules/n_/bin/n_3

> n_@1.4.5 postinstall /usr/local/lib/node_modules/n_
> npm pack lodash@^3 && targz extract lodash-3.*.tgz extraneous/lodash3

lodash-3.10.1.tgz
+ n_@1.4.5
added 26 packages in 11.852s
$ n_
n_ > _.toInteger('123')
123
n_ > 
```

**Comment by paul42** [comment]
@borisdiakur thanks for taking the time to reply - I must've done something wrong previously or been in a bad state, I uninstalled, reinstalled and the command worked fine! user error. Sorry for opening the issue.

Thanks so much for your time and the great library!

**Comment by borisdiakur** [comment]
No problem, you’re welcome!
